import type { RouteManifestItem } from "@/types/router";
import SetupLicenseWizardPage from "@/pages/setup/SetupLicenseWizardPage.vue";

import { routeIds } from "./route-ids";

export const routeManifest: RouteManifestItem[] = [
  {
    id: routeIds.setupLicenseWizard,
    path: "/setup/license",
    title: "首启与许可证向导",
    navGroup: "启动与总览",
    icon: "启动",
    pageType: "wizard",
    requiresLicense: false,
    requiresProjectContext: false,
    detailPanelMode: "hidden",
    statusBarMode: "setup",
    componentImport: "@/pages/setup/SetupLicenseWizardPage.vue",
    loadComponent: async () => ({ default: SetupLicenseWizardPage })
  },
  {
    id: routeIds.creatorDashboard,
    path: "/dashboard",
    title: "创作总览",
    navGroup: "启动与总览",
    icon: "总览",
    pageType: "dashboard",
    requiresLicense: true,
    requiresProjectContext: false,
    detailPanelMode: "contextual",
    statusBarMode: "overview",
    componentImport: "@/pages/dashboard/CreatorDashboardPage.vue",
    loadComponent: () => import("@/pages/dashboard/CreatorDashboardPage.vue")
  },
  {
    id: routeIds.scriptTopicCenter,
    path: "/scripts/topics",
    title: "脚本与选题中心",
    navGroup: "创作前置",
    icon: "脚本",
    pageType: "editor",
    requiresLicense: true,
    requiresProjectContext: true,
    detailPanelMode: "contextual",
    statusBarMode: "editing",
    componentImport: "@/pages/scripts/ScriptTopicCenterPage.vue",
    loadComponent: () => import("@/pages/scripts/ScriptTopicCenterPage.vue")
  },
  {
    id: routeIds.storyboardPlanningCenter,
    path: "/storyboards/planning",
    title: "分镜规划中心",
    navGroup: "创作前置",
    icon: "分镜",
    pageType: "editor",
    requiresLicense: true,
    requiresProjectContext: true,
    detailPanelMode: "contextual",
    statusBarMode: "editing",
    componentImport: "@/pages/storyboards/StoryboardPlanningCenterPage.vue",
    loadComponent: () => import("@/pages/storyboards/StoryboardPlanningCenterPage.vue")
  },
  {
    id: routeIds.videoDeconstructionCenter,
    path: "/video/deconstruction",
    title: "视频拆解中心",
    navGroup: "创作前置",
    icon: "拆解",
    pageType: "workspace",
    requiresLicense: true,
    requiresProjectContext: true,
    detailPanelMode: "logs",
    statusBarMode: "review",
    componentImport: "@/pages/video/VideoDeconstructionCenterPage.vue",
    loadComponent: () => import("@/pages/video/VideoDeconstructionCenterPage.vue")
  },
  {
    id: routeIds.aiEditingWorkspace,
    path: "/workspace/editing",
    title: "AI 剪辑工作台",
    navGroup: "创作与媒体",
    icon: "剪辑",
    pageType: "workspace",
    requiresLicense: true,
    requiresProjectContext: true,
    detailPanelMode: "asset",
    statusBarMode: "editing",
    componentImport: "@/pages/workspace/AIEditingWorkspacePage.vue",
    loadComponent: () => import("@/pages/workspace/AIEditingWorkspacePage.vue")
  },
  {
    id: routeIds.voiceStudio,
    path: "/voice/studio",
    title: "配音中心",
    navGroup: "创作与媒体",
    icon: "配音",
    pageType: "editor",
    requiresLicense: true,
    requiresProjectContext: true,
    detailPanelMode: "contextual",
    statusBarMode: "editing",
    componentImport: "@/pages/voice/VoiceStudioPage.vue",
    loadComponent: () => import("@/pages/voice/VoiceStudioPage.vue")
  },
  {
    id: routeIds.subtitleAlignmentCenter,
    path: "/subtitles/alignment",
    title: "字幕对齐中心",
    navGroup: "创作与媒体",
    icon: "字幕",
    pageType: "editor",
    requiresLicense: true,
    requiresProjectContext: true,
    detailPanelMode: "contextual",
    statusBarMode: "editing",
    componentImport: "@/pages/subtitles/SubtitleAlignmentCenterPage.vue",
    loadComponent: () => import("@/pages/subtitles/SubtitleAlignmentCenterPage.vue")
  },
  {
    id: routeIds.assetLibrary,
    path: "/assets/library",
    title: "资产中心",
    navGroup: "创作与媒体",
    icon: "资产",
    pageType: "workspace",
    requiresLicense: true,
    requiresProjectContext: true,
    detailPanelMode: "asset",
    statusBarMode: "overview",
    componentImport: "@/pages/assets/AssetLibraryPage.vue",
    loadComponent: () => import("@/pages/assets/AssetLibraryPage.vue")
  },
  {
    id: routeIds.renderExportCenter,
    path: "/renders/export",
    title: "渲染与导出中心",
    navGroup: "创作与媒体",
    icon: "导出",
    pageType: "queue",
    requiresLicense: true,
    requiresProjectContext: true,
    detailPanelMode: "logs",
    statusBarMode: "rendering",
    componentImport: "@/pages/renders/RenderExportCenterPage.vue",
    loadComponent: () => import("@/pages/renders/RenderExportCenterPage.vue")
  },
  {
    id: routeIds.accountManagement,
    path: "/accounts",
    title: "账号管理",
    navGroup: "执行与治理",
    icon: "账号",
    pageType: "settings",
    requiresLicense: true,
    requiresProjectContext: false,
    detailPanelMode: "binding",
    statusBarMode: "system",
    componentImport: "@/pages/accounts/AccountManagementPage.vue",
    loadComponent: () => import("@/pages/accounts/AccountManagementPage.vue")
  },
  {
    id: routeIds.deviceWorkspaceManagement,
    path: "/devices/workspaces",
    title: "设备与工作区管理",
    navGroup: "执行与治理",
    icon: "设备",
    pageType: "settings",
    requiresLicense: true,
    requiresProjectContext: false,
    detailPanelMode: "binding",
    statusBarMode: "system",
    componentImport: "@/pages/devices/DeviceWorkspaceManagementPage.vue",
    loadComponent: () => import("@/pages/devices/DeviceWorkspaceManagementPage.vue")
  },
  {
    id: routeIds.automationConsole,
    path: "/automation/console",
    title: "自动化执行中心",
    navGroup: "执行与治理",
    icon: "自动",
    pageType: "queue",
    requiresLicense: true,
    requiresProjectContext: false,
    detailPanelMode: "logs",
    statusBarMode: "tasks",
    componentImport: "@/pages/automation/AutomationConsolePage.vue",
    loadComponent: () => import("@/pages/automation/AutomationConsolePage.vue")
  },
  {
    id: routeIds.publishingCenter,
    path: "/publishing/center",
    title: "发布中心",
    navGroup: "执行与治理",
    icon: "发布",
    pageType: "queue",
    requiresLicense: true,
    requiresProjectContext: true,
    detailPanelMode: "binding",
    statusBarMode: "publishing",
    componentImport: "@/pages/publishing/PublishingCenterPage.vue",
    loadComponent: () => import("@/pages/publishing/PublishingCenterPage.vue")
  },
  {
    id: routeIds.reviewOptimizationCenter,
    path: "/review/optimization",
    title: "复盘与优化中心",
    navGroup: "执行与治理",
    icon: "复盘",
    pageType: "workspace",
    requiresLicense: true,
    requiresProjectContext: true,
    detailPanelMode: "logs",
    statusBarMode: "review",
    componentImport: "@/pages/review/ReviewOptimizationCenterPage.vue",
    loadComponent: () => import("@/pages/review/ReviewOptimizationCenterPage.vue")
  },
  {
    id: routeIds.aiSystemSettings,
    path: "/settings/ai-system",
    title: "AI 与系统设置",
    navGroup: "系统与 AI",
    icon: "设置",
    pageType: "settings",
    requiresLicense: true,
    requiresProjectContext: false,
    detailPanelMode: "settings",
    statusBarMode: "system",
    componentImport: "@/pages/settings/AISystemSettingsPage.vue",
    loadComponent: () => import("@/pages/settings/AISystemSettingsPage.vue")
  }
];
